openapi: 3.0.0
info:
  title: Space Tourism
  description: Space Tourisms API
  version: 1.0.0

servers:
  - url: https://space-tourism-backend-production.up.railway.app/
    description: server
  - url: http://localhost:3000
    description: local server

paths:
  /destination/{name}:
    get:
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Data retrieved successfully
  /crew/{name}:
    get:
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Data retrieved successfully
  /technology/{name}:
    get:
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Data retrieved successfully
